loomx.loom_version="1.17-SNAPSHOT"


mod.id = "replanter"
mod.name = "Replanter"
mod.group = "xyz.imide"
mod.version = "2.0.0"
mod.channel_tag = ""
mod.description = "A relatively small and simple mod made with Kotlin for automatically replanting crops after harvesting"
mod.authors = ["imide"]
mod.contributors = []
mod.inception_year = "2026"
mod.license.name = "AGPLv3"
mod.license.url = "https://opensource.org/license/agpl-3-0"
mod.license.dist = "repo"
mod.sources_url = "https://github.com/imide/replanter"
mod.homepage_url = "https://github.com/imide/replanter"
mod.issues_url = "https://github.com/imide/replanter/issues"
mod.discord_url = ""
mod.environment = "client"

[[mod.pom.developers]]
id = "imide"
name = "imide"
url = "https://github.com/imide"

[fabric]
deps.fabric-loader = "0.19.3"
deps.fabric-language-kotlin = "1.13.13+kotlin.2.4.10"

[fabric."1.21.1"]
deps.minecraft = "1.21.1"
deps.fabric-api = "0.116.7+1.21.1"
deps.modmenu = "15.0.0"
deps.yacl = "3.8.1+1.21.1-fabric"

[fabric."26.1.2"]
deps.minecraft = "26.1.2"
deps.fabric-api = "0.146.1+26.1.2"
deps.modmenu = "18.0.0-alpha.8"
deps.yacl = "3.9.6+26.1-fabric"
publish.additionalVersions = ["26.1.1", "26.1"]

[fabric."26.2"]
deps.minecraft = "26.2"
deps.fabric-api = "0.156.0+26.2"
deps.modmenu = "20.0.1"
deps.yacl = "3.9.6+26.2-fabric"

[neoforge]

[neoforge."1.21.1"]
deps.minecraft = "1.21.1"
deps.neoforge = "21.1.213"
deps.yacl = "3.8.1+1.21.1-neoforge"
deps.kotlin-for-forge = "5.12.0"

[neoforge."26.1.2"]
deps.minecraft = "26.1.2"
deps.neoforge = "26.1.2.29-beta"
deps.yacl = "3.9.6+26.1-neoforge"
deps.kotlin-for-forge = "6.0.0"
publish.additionalVersions = ["26.1.1", "26.1"]

[neoforge."26.2"]
deps.minecraft = "26.2"
deps.neoforge = "26.2.0.48-beta"
deps.yacl = "3.9.6+26.2-neoforge"
deps.kotlin-for-forge = "6.0.0"
